Repository MicrosoftDocs/azure-docs.nl-nl, pull requests merged in 2018-12, with the labels that each got.

#113 Update configuration.md
  articles/blockchain/workbench/configuration.md
Labels: In Progress, Linguistic Suggestion

#115 Update architecture.md
  articles/blockchain/workbench/architecture.md
Labels: Accepted, Linguistic Suggestion

#117 Fix typo and fix indents and fix display collapse
  articles/cognitive-services/Content-Moderator/ecommerce-retail-catalog-moderation.md
Labels: Accepted, Linguistic Suggestion, Source Issue
