Repository MicrosoftDocs/azure-docs.nl-nl, pull requests merged in 2019-04, with the labels that each got.

#227 Update quickstart-v2-uwp.md
  articles/active-directory/develop/quickstart-v2-uwp.md
Labels: In Progress, Source Issue

#236 Update vs-storage-aspnet5-getting-started-blobs.md
  articles/visual-studio/vs-storage-aspnet5-getting-started-blobs.md
Labels: Accepted, Linguistic Suggestion

#240 Fix mistranslation
  articles/azure-monitor/platform/api-alerts.md
Labels: Accepted, In Progress

#239 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-data-warehouse-connector.md
Labels: Accepted, In Progress

#238 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, In Progress

#237 Fix mistranslation
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, In Progress

#244 Fix mistranslation
  articles/data-factory/connector-azure-search.md
Labels: Accepted, In Progress, Linguistic Suggestion

#243 Fix mistranslation
  articles/azure-monitor/platform/archive-diagnostic-logs.md
Labels: Accepted, In Progress, Linguistic Suggestion

#242 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress, Linguistic Suggestion

#241 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-connector.md
Labels: Accepted, In Progress, Linguistic Suggestion

#245 Fix mistranslation
  articles/azure-monitor/insights/wire-data.md
Labels: Accepted, In Progress, Linguistic Suggestion

#246 Fix mistranslation
  articles/azure-monitor/platform/activity-logs-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#247 Fix mistranslation
  articles/data-factory/connector-azure-sql-database-managed-insance.md
Labels: Accepted, In Progress, Linguistic Suggestion

#248 Fix mistranslation
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, In Progress, Linguistic Suggestion

#250 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted, In Progress

#249 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted, In Progress

#252 Fix mistranslation
  articles/azure-maps/geofence-geojson.md
Labels: Accepted, In Progress

#251 Fix mistranslation
  articles/api-management/api-management-product-templates.md
Labels: Accepted, In Progress

#255 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, In Progress

#254 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted, In Progress

#253 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, In Progress

#258 Fix mistranslation
  articles/api-management/api-management-page-templates.md
Labels: Accepted, In Progress

#256 Fix mistranslation
  articles/data-factory/control-flow-filter-activity.md
Labels: Accepted, In Progress

#257 Fix mistranslation
  articles/automation/automation-dsc-diagnostics.md
Labels: Accepted, In Progress

#262 Fix mistranslation
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, In Progress

#261 Fix mistranslation
  articles/azure-monitor/insights/vminsights-log-search.md
Labels: Accepted, In Progress

#260 Fix mistranslation
  articles/api-management/api-management-howto-properties.md
Labels: Accepted, In Progress

#259 Fix mistranslation
  articles/api-management/api-management-error-handling-policies.md
Labels: Accepted, In Progress

#264 Fix mistranslation
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, In Progress

#263 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-search-connector.md
Labels: Accepted, In Progress
