Repository MicrosoftDocs/azure-docs.nl-nl, pull requests merged in 2019-07, with the labels that each got.

#423 Fix mistranslation
  articles/azure-monitor/platform/autoscale-webhook-email.md
Labels: Accepted

#424 Fix mistranslation
  articles/azure-monitor/platform/powershell-quickstart-samples.md
Labels: Accepted

#426 Fix mistranslation
  articles/blockchain/service/send-transaction.md
Labels: Accepted

#425 Fix mistranslation
  articles/blockchain/service/manage-consortium-powershell.md
Labels: Accepted

#427 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#428 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted, Linguistic Suggestion

#430 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, Linguistic Suggestion

#432 Fix mistranslation
  articles/data-factory/v1/data-factory-spark.md
Labels: Accepted

#431 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted

#433 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted

#434 Fix mistranslation
  articles/hdinsight/domain-joined/apache-domain-joined-create-configure-enterprise-security-cluster.md
Labels: Accepted

#435 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-adf.md
Labels: Accepted, Linguistic Suggestion

#436 Fix mistranslation
  articles/mariadb/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#438 Fix mistranslation
  articles/mysql/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#437 Fix mistranslation
  articles/mariadb/tutorial-design-database-cli.md
Labels: Accepted, Linguistic Suggestion

#440 Fix mistranslation
  articles/postgresql/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#439 Fix mistranslation
  articles/mysql/tutorial-design-database-using-cli.md
Labels: Accepted, Linguistic Suggestion

#441 Fix mistranslation
  articles/app-service-mobile/app-service-mobile-ios-get-started-offline-data.md
Labels: Accepted

#443 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, Linguistic Suggestion

#442 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#444 Fix mistranslation
  articles/service-bus-messaging/service-bus-amqp-protocol-guide.md
Labels: Accepted

#445 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Linguistic Suggestion

#447 Fix mistranslation
  articles/azure-functions/functions-reference-node.md
Labels: Accepted

#450 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted

#452 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted

#454 Fix mistranslation
  articles/azure-monitor/platform/powershell-quickstart-samples.md
Labels: Accepted

#453 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted

#455 Fix mistranslation
  articles/azure-resource-manager/resource-group-authoring-templates.md
Labels: Accepted

#457 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-string.md
Labels: Accepted

#456 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: Accepted

#458 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#459 Fix mistranslation
  articles/blockchain/workbench/messages-overview.md
Labels: Accepted

#460 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted

#463 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted, Linguistic Suggestion

#462 Update overview.md
  articles/lighthouse/overview.md
Labels: Accepted, Linguistic Suggestion

#466 Fix mistranslation
  articles/data-factory/connector-amazon-marketplace-web-service.md
Labels: Accepted, Linguistic Suggestion

#461 Update overview.md
  articles/lighthouse/overview.md
Labels: Linguistic Suggestion, Partially Accepted

#467 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted

#468 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted

#469 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, Linguistic Suggestion

#470 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted

#471 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted
