Repository MicrosoftDocs/azure-docs.nl-nl, pull requests merged in 2019-01, with the labels that each got.

#130 Translation translation omission
  articles/azure-functions/functions-host-json.md
Labels: Accepted, Technical Issue

#129 Translation translation omission
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Technical Issue

#128 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb.md
Labels: Accepted, Technical Issue

#127 Translation translation omission
  articles/data-factory/tutorial-copy-data-tool.md
Labels: Accepted, Technical Issue

#126 Translation translation omission
  articles/data-factory/concepts-pipeline-execution-triggers.md
Labels: Accepted, Technical Issue

#125 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, Technical Issue

#124 Translation translation omission
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Technical Issue

#123 Translation translation omission
  articles/data-factory/concepts-pipelines-activities.md
Labels: Accepted, Technical Issue

#135 Translation translation omission
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, Technical Issue

#136 Translation translation omission
  articles/data-factory/connector-azure-cosmos-db.md
Labels: Accepted, Technical Issue

#137 Translation translation omission
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted, Technical Issue

#138 Translation translation omission
  articles/data-factory/connector-azure-search.md
Labels: Accepted, Technical Issue

#139 Translation translation omission
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, Technical Issue

#140 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-copy-data-tool.md
Labels: Accepted, Technical Issue

#141 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-portal.md
Labels: Accepted, Technical Issue

#148 Translation translation omission
  articles/media-services/previous/media-services-overview.md
Labels: Accepted, Technical Issue

#147 Translation translation omission
  articles/media-services/previous/media-services-media-encoder-standard-formats.md
Labels: Accepted, Technical Issue

#145 Translation translation omission
  articles/data-factory/control-flow-expression-language-functions.md
Labels: Accepted, Technical Issue

#152 Translation translation omission
  articles/data-factory/v1/data-factory-usql-activity.md
Labels: Accepted, Technical Issue

#151 Translation translation omission
  articles/data-factory/v1/data-factory-use-custom-activities.md
Labels: Accepted, Technical Issue

#150 Translation translation omission
  articles/data-factory/v1/data-factory-sap-hana-connector.md
Labels: Accepted, Technical Issue

#149 Translation translation omission
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Technical Issue

#163 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted, Technical Issue

#161 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted, Technical Issue

#157 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-db2-connector.md
Labels: Accepted, Technical Issue

#182 Translation translation omission
  articles/data-factory/tutorial-hybrid-copy-data-tool.md
Labels: Accepted, Technical Issue

#181 Translation translation omission
  articles/data-factory/transform-data-using-stored-procedure.md
Labels: Accepted, Technical Issue

#183 Translation translation omission
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, Technical Issue

#188 Translation translation omission
  articles/data-factory/connector-ftp.md
Labels: Accepted, Technical Issue

#187 Translation translation omission
  articles/data-factory/connector-file-system.md
Labels: Accepted, Technical Issue

#185 Translation translation omission
  articles/data-factory/connector-cassandra.md
Labels: Accepted, Technical Issue

#201 Translation translation omission
  articles/data-factory/connector-sql-server.md
Labels: Accepted, Technical Issue

#200 Translation translation omission
  articles/data-factory/connector-sftp.md
Labels: Accepted, Technical Issue

#197 Translation translation omission
  articles/data-factory/connector-salesforce.md
Labels: Accepted, Technical Issue

#196 Translation translation omission
  articles/data-factory/connector-postgresql.md
Labels: Accepted, Technical Issue

#195 Translation translation omission
  articles/data-factory/connector-oracle.md
Labels: Accepted, Technical Issue

#193 Translation translation omission
  articles/data-factory/connector-odata.md
Labels: Accepted, Technical Issue

#164 Update create-cluster-cloud-shell.md
  articles/dev-spaces/how-to/create-cluster-cloud-shell.md
Labels: In Progress, Linguistic Suggestion

#165 Update share-dev-spaces.md
  articles/dev-spaces/how-to/share-dev-spaces.md
Labels: Accepted, Linguistic Suggestion

#166 Update manage-secrets.md
  articles/dev-spaces/how-to/manage-secrets.md
Labels: Accepted, Linguistic Suggestion

#169 Update upgrade-tools.md
  articles/dev-spaces/how-to/upgrade-tools.md
Labels: Accepted, In Progress, Linguistic Suggestion

#170 Update version-app.md
  articles/blockchain/workbench/version-app.md
Labels: Accepted, Linguistic Suggestion

#171 Update data-sources-reference.md
  articles/azure-monitor/platform/data-sources-reference.md
Labels: Accepted, Linguistic Suggestion

#202 Translation translation omission
  articles/data-factory/connector-sybase.md
Labels: Accepted, Technical Issue

#172 Update use-api.md
  articles/blockchain/workbench/use-api.md
Labels: Accepted, Linguistic Suggestion

#206 Fix missing
  articles/azure-functions/functions-twitter-email.md
Labels: Accepted, Linguistic Suggestion

#207 Fix missing
  articles/azure-maps/consumption-model.md
Labels: Accepted, Linguistic Suggestion

#209 Fix missing
  articles/azure-monitor/log-query/examples.md
Labels: Accepted, Linguistic Suggestion

#216 Fix missing
  articles/logic-apps/logic-apps-create-variables-store-values.md
Labels: Accepted, Linguistic Suggestion

#213 Corrected machine translation
  articles/blockchain/workbench/integration-patterns.md
Labels: In Progress, Linguistic Suggestion

#214 Fix missing
  articles/cognitive-services/LUIS/luis-container-configuration.md
Labels: Accepted, Linguistic Suggestion
